### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by ctessum**

### CODE REVIEW

**Comment by ctessum** [comment]
Here are some changes. I think in order for it to really work, however, gobra needs to change so that only sends the arguments that the user has _changed_ back to the server, rather than all arguments. I don't know how to do that, so if you can make that one change I can deal with the rest.

**Comment by khoin** [comment]
> change so that only sends the arguments that the user has changed back to the server, rather than all arguments.

Done. Will be updated with PR to spatialmodel/inmap:gobra

**Comment by khoin** [comment]
Chris, it seems that `dep` has made it so that whenever I run `go run main.go` it uses an older version of Gobra instead the one that's living on my machine? Some changes (such as the one mentioned above) is in Gobra, and is not going along with what Inmap's Gobra is using. Is there a way to force it using the local version? 

If not, I can do a PR on Inmap separately from Gobra, and we will have to move Inmap's Gobra's dependent version up.

**Comment by ctessum** [comment]
You can force it to use the local version by deleting everything in the
vendor directory.

I have a suspicion about what is causing the duplicate flags. I will look
into it.

**Comment by ctessum** [comment]
https://golang.org/cmd/go/#hdr-Vendor_Directories

**Pull request merged**
